### ISSUE TITLE
Support defining a namespace in a task manifest using an arbitrary separator

### ISSUE THREAD

**Issue by jcooklin** [intelsdi-x/snap#1068]
Stated another way, allow plugins to provide "/" as a valid character in the `Value` field of `NamespaceElement`.

This issue was brought up in https://github.com/intelsdi-x/snap-plugin-collector-df/issues/10 where it would be more natural if the framework allowed "/" as a valid character in the `Value` field of `NamespaceElement`.  

I propose that 
- The framework detect what separator is being used when reading a task manifest by peaking at the first character  
  - For instance, when a path (e.g. /sys/fs/cgroup) is being used as a `Value` of one of the `NamespaceElement`s the separator `%` could be used (e.g. "%intel%procfs%filesystem%/sys/fs/cgroup%space_free")  
- The `String` method on `Namespace` automatically selects the appropriate separator

Example metric catalog output given the above proposal

```
NAMESPACE                                                                         
/intel/mock/*/baz                                                                     
/intel/mock/bar                                                                         
/intel/mock/foo                                                                         
%intel%procfs%filesystem%/sys/fs/cgroup%space_free      
```

Example task manifest

``` yaml
---
  version: 1
  schedule:
    type: "simple"
    interval: "1s"
  max-failures: 10
  workflow:
    collect:
      metrics:
        /intel/mock/foo: {}
        /intel/mock/bar: {}
        /intel/mock/*/baz: {}
       %intel%procfs%filesystem%/sys/fs/cgroup%space_free: {}
      config:
        /intel/mock:
          name: "root"
          password: "secret"
      process:
        -
          plugin_name: "passthru"
          process: null
          publish:
            -
              plugin_name: "mock-file"
              config:
                file: "/tmp/snap_published_mock_file.log"
```
