### ISSUE TITLE
Task list not consistent

### ISSUE THREAD

**Issue by felipewd** [intelsdi-x/snap#1154]
Hi,

When listing tasks, if I run `snapctl task list` a few times, the tasks are listed in different ways (not always, but a few times).

This lead me to almost stop the wrong task, and I can see other people making the same mistake I did in a production environment.

I talked it over on Slack, and @IRCody suggested listing the tasks ordered by time created, which I agree.

If you guys could take a look, that'd great.

**Comment by IRCody** [comment]
After a brief look I think the best place to change this would be in [snapctl](https://github.com/intelsdi-x/snap/blob/master/cmd/snapctl/task.go#L479). I think sorting it before going into this loop is all that would be required.

**Comment by andrzej-k** [comment]
Hey @felipewd, maybe this is obvious, and you probably know about this, but you can give task a name, that may allow to better identify tasks. 
That is --name, or -n switch for ```snapctl task create```, or using ```name``` as part of task manifest:
```
---
  version: 1
  name: "task_name_here"
  schedule:
    type: "simple"
    interval: "1s"
  max-failures: 10
  workflow:
    collect:
      metrics:
```
