### ISSUE TITLE
Enable the collection of optional metrics

### ISSUE THREAD

**Issue by jcooklin** [intelsdi-x/snap#1190]
Today when you define a task it will fail if it doesn't exist in the catalog.  This becomes problematic when trying to use the same task across many servers which may not be exactly the same.

Proposal:
When defining the metrics to be collected in the task manfiest provide the ability to set a flag declaring the metric as optional.  The result being that if the metric cannot be collected it will be ignored and not cause the task to fail.

```yaml
  version: 1
  schedule:
    type: "simple"
    interval: "1s"
  workflow:
    collect:
      metrics:
        /intel/mock/*/baz: {optional: true}
```

**Comment by mjbrender** [comment]
I know of at least two users of Snap who would like to see this. +1 to the format of it - it's simple and looks like it wouldn't break existing Task Manifests.

**Comment by IRCody** [comment]
If a task manifest has multiple metrics like:
```yaml
 version: 1
  schedule:
    type: "simple"
    interval: "1s"
  workflow:
    collect:
      metrics:
        /intel/mock/*/baz: {optional: true}
        /intel/mock/foo: {}
```

Where both metrics map to the same collector. What happens when an error is returned from the collect call but some metrics are also returned? Since snap doesn't control the format of the error I think it might be tough to know which requested metrics were successfully returned.

The ways I see to address this:

* On collectMetrics return, if there is an error, we could check all the metrics comparing them against the requested metrics and verifying that any that are not tagged as optional have been returned.
* Make two separate collectMetrics calls in the case of mixed optional/non-optional metrics. One with just optional ones where we ignore any errors and one with non-optional ones where we fail on any errors.

**Comment by elemoine** [comment]
Thanks for creating this issue. FWIW we also need that functionality.

**Comment by andrzej-k** [comment]
Agree, that this would be useful feature, but how about making each metric optional by default? Only when marked as required but not available task would fail.

**Comment by candysmurf** [comment]
Agreed, it could be a useful feature by allowing optional metrics.  I still like to share a couple points for discussion.

* The benefit of task manifest is that it can pick and choose what to be collected instead of collecting all metrics. 

* Users can group metrics in different task manifests and create many tasks.

* Validating available metrics seems a good feature up front. 

I know with the optional metrics, it'll not stop the above. I just want to think any implication, such as,

*  Is it good to know what my system is collecting?
*  Will it affect the add/stop/disable task capability?





-

**Comment by andrzej-k** [comment]
@jcooklin To continue discussion on how to specify optional metrics - how about expanding **metrics** section to include children: **mandatory** and **optional**? Maybe that could be more convenient to use:
```yaml
  version: 1
  schedule:
    type: "simple"
    interval: "1s"
  workflow:
    collect:
      metrics:
        mandatory:
          /intel/mock/*/baz
        optional:
          /intel/mock/bar
```
