### ISSUE TITLE
Tasks don't reflect changes to plugin config

### ISSUE THREAD

**Issue by jcooklin** [intelsdi-x/snap#1222]
To reproduce add a plugin configuration item that will be used by a given task, start the given task and then update the configuration item.  

**Expected result**: When a task, depending on a configuration item that is not provided by the task, is changed the task should start using this new configuration item.
**Actual result**: The new configuration is ignored.

In the example below:
1. snapd is started with the following config. 
2. Plugins snap-plugin-collector-mock1 and snap-plugin-publisher-mock-file are loaded.
3. The task is left to run for 5 seconds.
4. The plugin-config for mock-file is updated 
 * `curl -X PUT --data '{"file": "/tmp/snap/snap-file2.out"}' http://localhost:8181/v1/plugins/publisher/mock-file/3/config`

```yaml
---
control:
  plugins:
    publisher:
      mock-file:
        all:
          file: /tmp/snap/snap-file.out
          test: true
```

![ex](https://www.dropbox.com/s/f9i8hq1e3p57k97/task-create.gif?raw=1)
