### ISSUE TITLE
Seed node does not join the cluster after restart

### ISSUE THREAD

**Issue by ralberto** [intelsdi-x/snap#1283]
A cluster of 3 nodes was started using the tribe configuration below:

```
tribe:
  enable: true
  bind_addr: 0.0.0.0
  bind_port: 6000
  seed: 10.112.226.139
```

Executing `snapctl member list` shows all three nodes. However if we restart seed node, it does not join the cluster again. Other nodes join the cluster without any problem!
