### ISSUE TITLE
Errors returned in the publish (grpc) response are ignored

### ISSUE THREAD

**Issue by jcooklin** [intelsdi-x/snap#1450]
If a grpc based plugin returns an error in the publish reply object the framework ignores the error and continues like it was a successful execution of the workflow.  

The task given below should eventually go into a disabled state however currently the error is undetected when it's passed back in the reply object.
```
rand-file.yml
---
  version: 1
  schedule:
    type: "simple"
    interval: "1s"
  workflow:
    collect:
      metrics:
        /random/integer: {}
      publish:
        -
          plugin_name: test-file-publisher
          config:
            file: /tmp/rand-file.out
            return_error: true
```
![before](https://www.dropbox.com/s/7v4jek51nfi4ak7/before.gif?raw=1)
