### ISSUE TITLE
Global plugin config values are not being set properly 

### ISSUE THREAD

**Issue by jcooklin** [intelsdi-x/snap#1495]
When snap is started with a config and a plugin has a config item with a default value the value provided in the config (the one snap was started with) should override the plugins default value.

**Given**: `snapteld --config config.yml`
**Run**: `snaptel task create -t task.yml`

**config.yml**:
```
---
control:
  plugins:
    collector:
      mock:
        all:
          name: jane
```
**task.yml**:
```
---
version: 1
schedule:
    type: simple
    interval: 1s

workflow:
    collect:
        metrics:
            "/intel/mock/foo":
```

**Current result**: The above will result in the config`{'name': 'bob'}` being associated to `/intel/mock/foo`

**Expected result**: The config on `/intel/mock/foo` should be `{'name': 'jane'}`
