### ISSUE TITLE
Plugin Wanted: Graphite Streaming Collector

### ISSUE THREAD

**Issue by jtlisi** [intelsdi-x/snap#1587]
With the recent creation of streaming plugins, one plugin I had in mind was a graphite streaming plugin.

The plugin will accept metrics in the graphite metric format over the plaintext or pickle protocol. 
> *Plaintext*: `<metric path> <metric value> <metric timestamp>`

> *Pickle*: `[(path, (timestamp, value)), ...]`

This collector would utilize a model similar to the SNMP collector by updating the metric catalog using a set-file. It would translate metrics into the snap data model as follows.

metric: `http_requests.count.status.200.index 105 1491304254`

rule:
```yaml
rules:
  - expression: 'http_request.count.status.*.*'
     namespace:
       - http_request
       - count
       - 1                       # Translates the first wildcard element
         name: 'status_code'
         description: 'http status code'
       - 2                       # Translates the second wildcard element
         name: 'endpoint'
         description: 'url endpoint'
       - status
    tags: 
      example_tag_wildcard: 1
      example_tag_string: 'tag'
    description: 'description of this metric'
    unit: 'unit of this metric'
    config:
      etc...
```

I think a collector like this would be very useful and allow snap to integrate more tightly with the current graphite streaming ecosystem. The use case I have in mind is configuring [springboot](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-metrics.html) to stream metrics directly to snap. Let me know what you guys think and if you have any suggestions or better ways to do this.

Thanks!
