### ISSUE TITLE
Snap throws error on plugin unload, but continues to work

### ISSUE THREAD

**Issue by mkleina** [intelsdi-x/snap#1682]
Scenario:
1. Load mock1 collector
2. Load mock2 collector
3. **Create task for mock collectors** (needed to reproduce error), for example:
```yaml
version: 1
schedule:
  type: "simple"
  interval: "5s"
max-failures: 10
workflow:
  collect:
    metrics:
      /intel/mock/*: {}
    config:
      "/intel/mock":
        "password": "P@ssw0rd"
```
3. Unload **latest version** of collector - mock2
4. Error appears in log immediately:
```
ERRO[2017-07-11T10:20:20+02:00] unable to get loaded plugin                   _block=handle-unsubscription _module=control-runner error=plugin not found plugin-name=mock plugin-type=collector plugin-version=2 pool-count=1 pool-subscription-count=0
```

Unloading older version of plugin (mock1) or unloading plugin with no running task which uses the plugin, does not throw any error.
