### ISSUE TITLE
Update task examples with clear guidelines on when you need to use config 

### ISSUE THREAD

**Issue by mjbrender** [intelsdi-x/snap#786]
There was a convention, early on in the project, to give example user/password values in the configuration section of a task - @geauxvirtual and I discussed this on #770. It's unclear when a user/password is needed and when it is not. Example: 

```
     config:      
        /intel:     
         user: “snapd”
         password: “secret”
```

This issue is opened to go through all example task files and clarify. For instance: 

* Do I need to have a user & password in every task file? Does it depend on other binary's like snapd, snapctl or the plugins themselves?
