### ISSUE TITLE
Support ENV variables inside configuration files for paths

### ISSUE THREAD

**Issue by geauxvirtual** [intelsdi-x/snap#791]
When a snapd flag is set on the command line with an environment variable as part of the value such as `snapd -a $PATH/to/somewhere` the cli package we use will expand `$PATH` before passing the value into snapd. Support should be added for expanding environment variables from configurations set inside of config files before we try to use the values inside of snapd.

The below example should work:

``` yaml

---
control:
  auto_discover_path: $SNAP_PATH/plugin
```
