### ISSUE TITLE
A plugin fails to start when a task references metrics from two versions of the same plugin.

### ISSUE THREAD

**Issue by jcooklin** [intelsdi-x/snap#820]
Given two different versions of the same plugin where the first plugin contains a metric that is no longer exposed in version 2 the first plugin will not be started and the task fails.

**To recreate the scenario:**
* Start snap with the following config
```
---
control:
  plugins:
    collector:
      mock:
        versions:
          1:
            test: true
```
* Load the mock plugins (versions 1 and 2)
* Create and start the following task
```
---
  version: 1
  schedule:
    type: "simple"
    interval: "1s"
  workflow:
    collect:
      metrics:
        /intel/*: {}
      config:
        /intel/mock:
          user: "root"
          password: "secret"
```
