### ISSUE TITLE
Collect Tags not working

### ISSUE THREAD

**Issue by iceycake** [intelsdi-x/snap#978]
I'm developing a publisher plugin and want to publish the tags for collect as well.

I'm following the sample task @ https://github.com/intelsdi-x/snap/blob/master/scheduler/wmap/sample/1.yml to create tags for the collector and created the following task configuration:

```
---
  version: 1
  schedule: 
    type: "simple"
    interval: "1s"
  workflow: 
    collect: 
      metrics: 
        /intel/mock/foo: {}
        /intel/mock/bar: {}
        /intel/mock/*/baz: {}
      config: 
        /intel/mock: 
          name: "root"
          password: "secret"
      tags:
        /intel:
          region: "us-east-1"
          cluster: "cluster_xyz"
      process: 
        -   
          plugin_name: "passthru"
          process: null
          publish: 
            -   
              plugin_name: "cloudwatch"
              config: 
                region: "us-east-1"
                namespace: "cluster_xyz"
```

In my code, I did

```
	tags := m.Tags()

	dimensions := make([]*cloudwatch.Dimension, len(tags), len(tags))
	index := 0
	for k, v := range tags {
		logger.Printf("Dimension Key: %s, Value: %s", k, v)

		dimensions[index] = &cloudwatch.Dimension{
			Name: aws.String(k),
			Value: aws.String(v),
		}

		index++
	}

	return dimensions
```

However, it looks like m.Tags() only contains "plugin_running_on".

Am I doing anything wrong?

```
$ build/bin/snapd --version
snapd version v0.14.0-beta-2-g3777f43
```
